### ISSUE TITLE
OSX Test Failing: 'Poly' is not iterable...

### ISSUE THREAD

**Issue by RexFuzzle** [sfepy/sfepy#302]
I have the following two tests failing on a fresh in place build on osx:
tests/test_input_nodal_lcbcs.py
---   test_input: failed!
tests/test_mesh_smoothing.py
---   test_mesh_smoothing: failed!
When running in debug I get the following error:
  File "~/Repos/sfepy/sfepy/discrete/fem/lcbc_operators.py", line 393, in __init__
    if uu in poly:
TypeError: argument of type 'Poly' is not iterable

**Comment by rc** [comment]
Thanks for the report. Could you post here the "Required and optional packages found" list that is displayed after the build command?

Also, to determine the reason for the second failure, you can do:

```
python run_tests.py tests/test_mesh_smoothing.py --debug
```

**Comment by RexFuzzle** [comment]
Required and optional packages found:

cython is available in version 0.23.1
numpy is available in version 1.10.1
scipy is available in version 0.16.0
matplotlib is available in version 1.4.3
pyparsing is available in version 2.0.3
tables is available in version 3.2.2
mayavi (optional) is available in version 4.4.3
sympy (optional) is available in version 0.7.6
igakit (optional) is available in version 0.1
petsc4py (optional) is available in version 3.6.0
mpi4py (optional) is available in version 1.3.1
pymetis (optional) is available in version 2014.1
scikits.umfpack (optional) is available in version 0.1
pysparse (optional) is available in version 1.3-dev

Output for the second failing test-

python run_tests.py tests/test_mesh_smoothing.py --debug
<<< directory: tests, test files: 1
<<< tests/test_mesh_smoothing.py
sfepy: left over: ['verbose', '__builtins__', '_filename', '__file__', 'get_volume', '__package__', '__doc__', '__name__', 'TestCommon', 'op']
>>> test instance prepared (1 test(s))
sfepy: reading mesh [line2, tri3, quad4, tetra4, hexa8] (~/Repos/sfepy/meshes/3d/cylinder.vtk)...
sfepy: ...done in 0.02 s
>>> <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "run_tests.py", line 206, in <module>
    main()
  File "run_tests.py", line 197, in main
    run_tests(stats, dirname, [filename])
  File "run_tests.py", line 131, in run_tests
    n_fail, n_total, test_time = run_test(conf_name, options)
  File "run_tests.py", line 99, in run_test
    ok, n_fail, n_total = test.run(options.debug)
  File "~/Repos/sfepy/sfepy/base/testing.py", line 58, in run
    ret = test_method()
  File "~/Repos/sfepy/tests/test_mesh_smoothing.py", line 45, in test_mesh_smoothing
    vol0 = get_volume(conn, mesh.coors)
  File "~/Repos/sfepy/tests/test_mesh_smoothing.py", line 26, in get_volume
    vols = mul * dets_fast(mtx)
  File "~/Repos/sfepy/sfepy/linalg/utils.py", line 83, in dets_fast
    lapack_routine = lapack_lite.dgetrf
AttributeError: 'module' object has no attribute 'dgetrf'

**Comment by rc** [comment]
The second one should be fixed in [1] - could you verify? (add https://github.com/rc/sfepy.git as a remote).

[1] https://github.com/rc/sfepy/commit/a3a0847791e4280ae6972e719435c662803ff7aa

**Comment by RexFuzzle** [comment]
I get the following error with [1]
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/version.py", line 296, in __cmp__
    return cmp(self.version, other.version)
AttributeError: 'float' object has no attribute 'version'

I think it needs the 1.8 to be in LooseVersion too- i.e. >= LooseVersion('1.8')

**Comment by RexFuzzle** [comment]
Just confirmed- it does work with LooseVersion('1.8')

**Comment by rc** [comment]
Or just a string 1.8 is OK - as in the new commit... I was too quick to push. Thanks for testing.

**Comment by rc** [comment]
It's now fixed in the master.

**Comment by rc** [comment]
As for the first one, it seems that determining coefficients of a polynomial in sympy is difficult to do so that it works across versions.

**Comment by rc** [comment]
The first one should be fixed at https://github.com/rc/sfepy/commit/a79feccd4110820a9d8e0a22b07a417ecb2d4221

**Comment by RexFuzzle** [comment]
Yip, fixed. Thank you so much!

**Comment by rc** [comment]
OK, let's close this. Thanks for reporting the problem!
