### ISSUE TITLE
`meshio_Cells` got an unexpected keyword argument 'type'

### ISSUE THREAD

**Issue by WhymustIhaveaname** [sfepy/sfepy#769]
I just somehow installed SfePy and I am running the `poisson_short_syntax.py` following the tutorial. Now I get the following error
```
...
sfepy: nls: iter: 0, residual: 1.176265e-01 (rel: 1.000000e+00)
sfepy:   residual:    0.00 [s]
sfepy:     matrix:    0.00 [s]
sfepy:      solve:    0.00 [s]
sfepy: nls: iter: 1, residual: 1.755447e-16 (rel: 1.492390e-15)
...
  File "/home/public/youran_Fem/sfepy/sfepy/discrete/fem/mesh.py", line 438, in write
    io.write(filename, self, out, **kwargs)
  File "/home/public/youran_Fem/sfepy/sfepy/discrete/fem/meshio.py", line 428, in write
    cell_sets) = self._create_out_data(mesh, out)
  File "/home/public/youran_Fem/sfepy/sfepy/discrete/fem/meshio.py", line 477, in _create_out_data
    cells.append(meshio_Cells(type=inv_cell_types[desc][0],
TypeError: __init__() got an unexpected keyword argument 'type'
``` 

It seems that the computation has been finished, the error happens during exporting. My meshio version is '5.2.2' and the result of `run_tests.py` is in the attachment.

[SfePy-test-result.txt](https://github.com/sfepy/sfepy/files/7910286/SfePy-test-result.txt)

**Comment by WhymustIhaveaname** [comment]
I found 'type' is renamed as 'cell_type' on 12 Dec 2021 in [this commit](https://github.com/nschloe/meshio/commit/fc84a4b16d275cf72bf9a564adc92094bf08c5df).

Modifying line 477 of `meshio.py` from
```
cells.append(meshio_Cells(type=inv_cell_types[desc][0],
```
to
```
cells.append(meshio_Cells(cell_type=inv_cell_types[desc][0],
```
solves this.

**Comment by WhymustIhaveaname** [comment]
And after this change, all the tests passed!
```
111 test file(s) executed in 315.07 s, 0 failure(s) of 206 test(s)
```
Only there is a warning by meshio
```
Warning: VTK format cannot write sets. Consider converting them to [point,cell]_data.
```

**Comment by rc** [comment]
Thanks for the debugging! It will be fixed soon - meshio is evolving fast, so currently sfepy works with meshio <= 4.4, but this is enforced only in the CI setup and the conda package.
