### ISSUE TITLE
Package conflicts

### ISSUE THREAD

**Issue by deng-cy** [sfepy/sfepy#546]
![image](https://user-images.githubusercontent.com/40417707/63135078-59902b00-bf9a-11e9-9731-83fb21ef1552.png)
I saw some conflict messages when installing sfepy.

**Comment by rc** [comment]
I can reproduce that. It seems that for some reason, the sfepy package or some of its dependencies(?) require Python 2.7. @BubuLK do you have any idea why is that?

**Comment by deng-cy** [comment]
I forgot to mention that the OS is Windows 10

**Comment by rc** [comment]
Thanks for the update. 

Before we fix the problem, you could try installing the sfepy dependencies into your anaconda, and then build sfepy from sources, see http://sfepy.org/doc-devel/installation.html#installing-sfepy-from-sources.

**Comment by BubuLK** [comment]
> I can reproduce that. It seems that for some reason, the sfepy package or some of its dependencies(?) require Python 2.7. @BubuLK do you have any idea why is that?

My guess: sfepy-feedstock pckages aren't build for Python 3.7 (see 1st incompatibility line in above log messages... Py27/36 works fine).

There shoudl be better (more specific) definition in sfepy-feedstock recipe meta.yml. I'll investigate in this issue.

**Comment by rc** [comment]
Thanks @BubuLK for the update. I have tried creating a Python 3.6 virtual environment:
```
conda create --name py36 python=3.6
conda activate py36
conda install sfepy
```
This installs sfepy-2018.4, but the tests fail on a scipy incompatibility:
```
    from scipy.misc import factorial
ImportError: cannot import name 'factorial'
```
Then I tried 
```
conda install sfepy=2019.2
```
which lead to
```
UnsatisfiableError: The following specifications were found                     
to be incompatible with the existing python installation in your environment:

  - sfepy=2019.2 -> python[version='2.7.*|>=2.7,<2.8.0a0']
  - sfepy=2019.2 -> python[version='<3']
  - sfepy=2019.2 -> python[version='>=2.7.15,<3.0a0']
```
It looks like no Python 3.x package is available at conda-forge?

**Comment by wd15** [comment]
I can't get Sfepy working with Conda and 2019.2. The following does work as an environment.yml
```
name: sfepy
channels:
  - conda-forge
dependencies:
  - python=3.6
  - sfepy=2018.2
```
Python 3.7 with either 2018.2 or 2019.2 gives me conflicts and 2019.2 with 3.6 gives me conflicts. Tried this just now.

**Comment by rc** [comment]
@deng-cy The new release 2019.3 is now available on conda-forge and should solve this issue. Reopen this, please, if the problem persists in your setup.

**Comment by deng-cy** [comment]
Yes, I successfully installed. Thanks.
